/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controleremoto;

//import java.util.Timer;
//import java.util.TimerTask;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.DefaultListModel;
import javax.swing.Timer;

/**
 *
 * @author Fernando
 */
public class Controle extends javax.swing.JFrame {

    /**
     * Creates new form Controle
     */
    public Controle() {
        initComponents();

        desliga();

        ControleRemotoObj = new ControleRemoto();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_1 = new javax.swing.JButton();
        btn_source = new javax.swing.JButton();
        btn_luz = new javax.swing.JButton();
        btn_liga = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_zero = new javax.swing.JButton();
        btn_precan = new javax.swing.JButton();
        btn_aumvol = new javax.swing.JButton();
        btn_mudo = new javax.swing.JButton();
        btn_aumcan = new javax.swing.JButton();
        btn_redcan = new javax.swing.JButton();
        btn_canlista = new javax.swing.JButton();
        btn_redvol = new javax.swing.JButton();
        btn_guia = new javax.swing.JButton();
        btn_smarthub = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        btn_tools = new javax.swing.JButton();
        btn_setaacim = new javax.swing.JButton();
        btn_info = new javax.swing.JButton();
        btn_setadir = new javax.swing.JButton();
        btn_enter = new javax.swing.JButton();
        btn_setaesq = new javax.swing.JButton();
        btn_return = new javax.swing.JButton();
        btn_setabaixo = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_a = new javax.swing.JButton();
        btn_futeb = new javax.swing.JButton();
        btn_status = new javax.swing.JButton();
        btn_more = new javax.swing.JButton();
        btn_manual = new javax.swing.JButton();
        btn_pip = new javax.swing.JButton();
        btn_lstservdds = new javax.swing.JButton();
        btn_avanc = new javax.swing.JButton();
        btn_pausa = new javax.swing.JButton();
        btn_retroc = new javax.swing.JButton();
        btn_3d = new javax.swing.JButton();
        btn_play = new javax.swing.JButton();
        btn_parar = new javax.swing.JButton();
        btn_d = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_ligado = new javax.swing.JLabel();
        lbl_canal = new javax.swing.JLabel();
        lbl_result = new javax.swing.JLabel();
        lbl_volume = new javax.swing.JLabel();
        lbl_source = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_canais = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btn_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_1.JPG"))); // NOI18N
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_source.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_source.JPG"))); // NOI18N
        btn_source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sourceActionPerformed(evt);
            }
        });

        btn_luz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_luz.JPG"))); // NOI18N
        btn_luz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luzActionPerformed(evt);
            }
        });

        btn_liga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_liga.JPG"))); // NOI18N
        btn_liga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ligaActionPerformed(evt);
            }
        });

        btn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_2.JPG"))); // NOI18N
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_3.JPG"))); // NOI18N
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_4.JPG"))); // NOI18N
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_5.JPG"))); // NOI18N
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_6.JPG"))); // NOI18N
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_7.JPG"))); // NOI18N
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_8.JPG"))); // NOI18N
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_9.JPG"))); // NOI18N
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_menos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_menos.JPG"))); // NOI18N
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        btn_zero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_0.JPG"))); // NOI18N
        btn_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zeroActionPerformed(evt);
            }
        });

        btn_precan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_precan.JPG"))); // NOI18N
        btn_precan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_precanActionPerformed(evt);
            }
        });

        btn_aumvol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_aumvol.JPG"))); // NOI18N
        btn_aumvol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aumvolActionPerformed(evt);
            }
        });

        btn_mudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_mute.JPG"))); // NOI18N
        btn_mudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudoActionPerformed(evt);
            }
        });

        btn_aumcan.setBackground(new java.awt.Color(0, 0, 0));
        btn_aumcan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_aumcan.JPG"))); // NOI18N
        btn_aumcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aumcanActionPerformed(evt);
            }
        });

        btn_redcan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_redcan.JPG"))); // NOI18N
        btn_redcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redcanActionPerformed(evt);
            }
        });

        btn_canlista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_chlist.JPG"))); // NOI18N
        btn_canlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_canlistaActionPerformed(evt);
            }
        });

        btn_redvol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_redvol.JPG"))); // NOI18N
        btn_redvol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redvolActionPerformed(evt);
            }
        });

        btn_guia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_guia.JPG"))); // NOI18N
        btn_guia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guiaActionPerformed(evt);
            }
        });

        btn_smarthub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_smarthub.JPG"))); // NOI18N
        btn_smarthub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_smarthubActionPerformed(evt);
            }
        });

        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_menu.JPG"))); // NOI18N
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_tools.setBackground(new java.awt.Color(0, 0, 0));
        btn_tools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_tools.JPG"))); // NOI18N
        btn_tools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toolsActionPerformed(evt);
            }
        });

        btn_setaacim.setBackground(new java.awt.Color(0, 0, 0));
        btn_setaacim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_setaup.JPG"))); // NOI18N
        btn_setaacim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setaacimActionPerformed(evt);
            }
        });

        btn_info.setBackground(new java.awt.Color(0, 0, 0));
        btn_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_info.JPG"))); // NOI18N
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });

        btn_setadir.setBackground(new java.awt.Color(0, 0, 0));
        btn_setadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_setadir.JPG"))); // NOI18N
        btn_setadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setadirActionPerformed(evt);
            }
        });

        btn_enter.setBackground(new java.awt.Color(0, 0, 0));
        btn_enter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_enter.JPG"))); // NOI18N
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });

        btn_setaesq.setBackground(new java.awt.Color(0, 0, 0));
        btn_setaesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_setaesq.JPG"))); // NOI18N
        btn_setaesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setaesqActionPerformed(evt);
            }
        });

        btn_return.setBackground(new java.awt.Color(0, 0, 0));
        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_return.JPG"))); // NOI18N
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });

        btn_setabaixo.setBackground(new java.awt.Color(0, 0, 0));
        btn_setabaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_setabaixo.JPG"))); // NOI18N
        btn_setabaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setabaixoActionPerformed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(0, 0, 0));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_exit.JPG"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_c.setBackground(new java.awt.Color(0, 0, 0));
        btn_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_c.JPG"))); // NOI18N
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });

        btn_b.setBackground(new java.awt.Color(0, 0, 0));
        btn_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_b.JPG"))); // NOI18N
        btn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bActionPerformed(evt);
            }
        });

        btn_a.setBackground(new java.awt.Color(0, 0, 0));
        btn_a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_a.JPG"))); // NOI18N
        btn_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aActionPerformed(evt);
            }
        });

        btn_futeb.setBackground(new java.awt.Color(0, 0, 0));
        btn_futeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_fut.JPG"))); // NOI18N
        btn_futeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_futebActionPerformed(evt);
            }
        });

        btn_status.setBackground(new java.awt.Color(0, 0, 0));
        btn_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_status.JPG"))); // NOI18N
        btn_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statusActionPerformed(evt);
            }
        });

        btn_more.setBackground(new java.awt.Color(0, 0, 0));
        btn_more.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_more.JPG"))); // NOI18N
        btn_more.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moreActionPerformed(evt);
            }
        });

        btn_manual.setBackground(new java.awt.Color(0, 0, 0));
        btn_manual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_manual.JPG"))); // NOI18N
        btn_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manualActionPerformed(evt);
            }
        });

        btn_pip.setBackground(new java.awt.Color(0, 0, 0));
        btn_pip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_pip.JPG"))); // NOI18N
        btn_pip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pipActionPerformed(evt);
            }
        });

        btn_lstservdds.setBackground(new java.awt.Color(0, 0, 0));
        btn_lstservdds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_dd.JPG"))); // NOI18N
        btn_lstservdds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lstservddsActionPerformed(evt);
            }
        });

        btn_avanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_avancar.JPG"))); // NOI18N
        btn_avanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avancActionPerformed(evt);
            }
        });

        btn_pausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_pausa.JPG"))); // NOI18N
        btn_pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pausaActionPerformed(evt);
            }
        });

        btn_retroc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_retroc.JPG"))); // NOI18N
        btn_retroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retrocActionPerformed(evt);
            }
        });

        btn_3d.setBackground(new java.awt.Color(0, 0, 0));
        btn_3d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_3d.JPG"))); // NOI18N
        btn_3d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3dActionPerformed(evt);
            }
        });

        btn_play.setBackground(new java.awt.Color(0, 0, 0));
        btn_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_play.JPG"))); // NOI18N
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });

        btn_parar.setBackground(new java.awt.Color(0, 0, 0));
        btn_parar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_stop.JPG"))); // NOI18N
        btn_parar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pararActionPerformed(evt);
            }
        });

        btn_d.setBackground(new java.awt.Color(0, 0, 0));
        btn_d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_d.JPG"))); // NOI18N
        btn_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VOL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_3d, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_play, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_parar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_retroc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_pausa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_avanc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_precan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_liga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_source, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(btn_luz, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_aumvol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_redvol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(7, 7, 7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_canlista, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_redcan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_mudo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_aumcan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_tools, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_setaacim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_info, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_smarthub, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_guia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_setaesq, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_setadir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_a, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_b, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_setabaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_d, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_futeb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_status, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_more, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_manual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pip, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_lstservdds, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_liga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luz, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(btn_source, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btn_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btn_7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_zero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btn_menos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_precan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_aumcan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_mudo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_aumvol, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_canlista, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_redcan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_redvol, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_guia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_smarthub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_setaacim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tools, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_info, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_setaesq, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_setadir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_setabaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_c, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btn_b, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btn_a, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_d))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btn_futeb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_more))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_pip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btn_manual, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(btn_lstservdds, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_pausa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_retroc, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(btn_avanc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_play, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3d, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_parar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ligado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ligado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ligado.setText("lig");
        jPanel2.add(lbl_ligado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, 30));

        lbl_canal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_canal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_canal.setText("can");
        jPanel2.add(lbl_canal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 110, 30));

        lbl_result.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_result.setForeground(new java.awt.Color(255, 255, 255));
        lbl_result.setText("Resultado");
        jPanel2.add(lbl_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 300, 100));

        lbl_volume.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_volume.setForeground(new java.awt.Color(255, 255, 255));
        lbl_volume.setText("vol");
        jPanel2.add(lbl_volume, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 100, -1));

        lbl_source.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_source.setForeground(new java.awt.Color(255, 255, 255));
        lbl_source.setText("source");
        jPanel2.add(lbl_source, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 290, -1));

        jList_canais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList_canais.setModel(listach);
        jScrollPane1.setViewportView(jList_canais);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 90, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TV.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

// Visibilidade
//    int statusliga;
    int numbtcanal, tpbtcanal;
    String numbtcanal2, canal = "";
    int canalnum = 0;

    private ControleRemoto ControleRemotoObj;

    String vetorch[] = new String[5];
    DefaultListModel listach = new DefaultListModel();
    int selecionado = 0;


    private void btn_ligaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ligaActionPerformed
        // TODO add your handling code here:

        ControleRemotoObj.ligadesl();

        lbl_ligado.setVisible(true);

        lbl_ligado.setText(ControleRemotoObj.statusliga);

        lbl_result.setVisible(false);

        if (ControleRemotoObj.getLigatv() == false) {
            desliga();
        };
    }//GEN-LAST:event_btn_ligaActionPerformed

    private void desliga() {
        lbl_ligado.setVisible(false);
        lbl_source.setVisible(false);
        lbl_canal.setVisible(false);
        lbl_volume.setVisible(false);
        lbl_result.setVisible(false);
        jList_canais.setVisible(false);
        jScrollPane1.setVisible(false);

        listach.removeAllElements();
    }


    private void btn_aumvolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aumvolActionPerformed
        // TODO add your handling code here:  
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            lbl_volume.setVisible(true);
            ControleRemotoObj.aumvolume();
            lbl_volume.setText("Volume " + (Integer.toString(ControleRemotoObj.getNumvolume())));    
//            lbl_volume.setText (Integer.toString(ControleRemotoObj.numvolume));
        }


    }//GEN-LAST:event_btn_aumvolActionPerformed

    private void btn_redvolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redvolActionPerformed
        // TODO add your handling code here:   
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            lbl_volume.setVisible(true);
            ControleRemotoObj.dimvolume();
            lbl_volume.setText("Volume " + (Integer.toString(ControleRemotoObj.getNumvolume())));
        }

    }//GEN-LAST:event_btn_redvolActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {

            carregacanal("1");

        }


    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_aumcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aumcanActionPerformed
        // TODO add your handling code here:
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            tpbtcanal = 1;
            lbl_canal.setVisible(true);

            //Guarda Pré Canal
            ControleRemotoObj.setPrecan((ControleRemotoObj.getNumcanal()));

            //Aumenta Canal
            ControleRemotoObj.aumcanal();
            canal = "";

            lbl_canal.setText("Canal " + (Integer.toString(ControleRemotoObj.getNumcanal())));

        }

    }//GEN-LAST:event_btn_aumcanActionPerformed

    private void btn_redcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redcanActionPerformed
        // TODO add your handling code here:        
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            lbl_canal.setVisible(true);

            //Guarda Pré Canal
            ControleRemotoObj.setPrecan((ControleRemotoObj.getNumcanal()));

            // Reduz Canal
            ControleRemotoObj.dimcanal();
            canal = "";
            lbl_canal.setText("Canal " + (Integer.toString(ControleRemotoObj.getNumcanal())));

        }
    }//GEN-LAST:event_btn_redcanActionPerformed

    private void btn_sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sourceActionPerformed
        // TODO add your handling code here:       
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            lbl_source.setVisible(true);
            ControleRemotoObj.source();
            lbl_source.setText(ControleRemotoObj.getSource());
//            lbl_source.setText("TV Screem Mirror HDMI1 HDMI2 USB1 USB2 ");
        }


    }//GEN-LAST:event_btn_sourceActionPerformed

    private void btn_mudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudoActionPerformed
        // TODO add your handling code here:        
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            lbl_volume.setVisible(true);
            ControleRemotoObj.mudo();
            lbl_volume.setText(ControleRemotoObj.getStatusvol());
//            lbl_volume.setText("MUDO");
        }
    }//GEN-LAST:event_btn_mudoActionPerformed

    private void btn_canlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_canlistaActionPerformed
        // TODO add your handling code here:

        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            lbl_result.setVisible(false);
            jScrollPane1.setVisible(true);
            jList_canais.setVisible(true);
            listach.removeAllElements();
            jList_canais.setModel(listach);

            //       String[] JlistItems = {"A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11"};
            String[] JlistItems = {"Canais", "3", "5", "7", "22", "44", "109"};
            for (int i = 0; i < JlistItems.length; i++) {
                listach.add(i, JlistItems[i]);
            }
            jList_canais.setSelectedIndex(1); // define a seleção para o novo item

//            vetorch[0] = ("Lista Canais");
//            listach.addElement(vetorch[0]);
//            vetorch[1] = "1";
//            listach.addElement("Canal " + vetorch[1]);
//            vetorch[2] = "2";
//            listach.addElement("Canal " + vetorch[2]);
//            vetorch[3] = "3";
//            listach.addElement("Canal " + vetorch[3]);
//            vetorch[4] = "4";
//            listach.addElement("Canal " + vetorch[4]);
        }


    }//GEN-LAST:event_btn_canlistaActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:        
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            carregacanal("2");
        }
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            carregacanal("3");
        }
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            carregacanal("4");
        }

    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            carregacanal("5");
        }
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            carregacanal("6");
        }
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            carregacanal("7");
        }
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            carregacanal("8");
        }
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            carregacanal("9");
        }
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zeroActionPerformed
        // TODO add your handling code here:
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            carregacanal("0");
        }
    }//GEN-LAST:event_btn_zeroActionPerformed

    private void btn_luzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luzActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.luzbotao();
            lbl_result.setText(ControleRemotoObj.getResult());
//            lbl_result.setText("Luz do Controle Ligada!");
        }

    }//GEN-LAST:event_btn_luzActionPerformed

    private void btn_smarthubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_smarthubActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.smarthub();
            lbl_result.setText(ControleRemotoObj.getResult());
            //        lbl_result.setText("Abrindo Smart Hub!");
        }

    }//GEN-LAST:event_btn_smarthubActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.menu();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_guiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guiaActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.guia();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_guiaActionPerformed

    private void btn_toolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toolsActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.tools();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_toolsActionPerformed

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.info();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_infoActionPerformed

    private void btn_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.func_a();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_aActionPerformed

    private void btn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.func_b();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_bActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.func_c();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.func_d();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_dActionPerformed

    private void btn_futebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_futebActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.futebol();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_futebActionPerformed

    private void btn_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statusActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.status();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_statusActionPerformed

    private void btn_moreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moreActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.more();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_moreActionPerformed

    private void btn_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manualActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.manual();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_manualActionPerformed

    private void btn_pipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pipActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.pip();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_pipActionPerformed

    private void btn_lstservddsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lstservddsActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.lstserv();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_lstservddsActionPerformed

    private void btn_retrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retrocActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.retroc();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_retrocActionPerformed

    private void btn_pausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pausaActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.pausa();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_pausaActionPerformed

    private void btn_avancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avancActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.avanc();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_avancActionPerformed

    private void btn_3dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3dActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.tresd();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_3dActionPerformed

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.play();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_playActionPerformed

    private void btn_pararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pararActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.stop();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_pararActionPerformed

    private void btn_precanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_precanActionPerformed
        // TODO add your handling code here:

        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setVisible(true);
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            lbl_canal.setVisible(true);

            lbl_canal.setText(Integer.toString(ControleRemotoObj.getPrecan()));

            ControleRemotoObj.setNumcanal(Integer.parseInt(lbl_canal.getText()));

            lbl_canal.setText("Canal " + Integer.toString(ControleRemotoObj.getPrecan()));

            canal = "";
        }
    }//GEN-LAST:event_btn_precanActionPerformed

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.retornar();
            lbl_result.setText(ControleRemotoObj.getResult());
        }

    }//GEN-LAST:event_btn_returnActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.sair();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.canaisdig();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_setadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setadirActionPerformed
        // TODO add your handling code here:
        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.botaodir();
            lbl_result.setText(ControleRemotoObj.getResult());
        }

    }//GEN-LAST:event_btn_setadirActionPerformed

    private void btn_setaesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setaesqActionPerformed
        // TODO add your handling code here:

        lbl_result.setVisible(true);
        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else {
            ControleRemotoObj.botaoesq();
            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_setaesqActionPerformed

    private void btn_setaacimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setaacimActionPerformed
        // TODO add your handling code here:

        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else if (jList_canais.getSelectedValue() == null) {

            ControleRemotoObj.botaoacima();
            lbl_result.setText(ControleRemotoObj.getResult());
            lbl_result.setVisible(true);
        } else {

// TODO add your handling code here:
            // botão para mover o item jlist selecionado para cima
            String selectedItem = jList_canais.getSelectedValue(); // obter o valor do item
            int itemIndex = jList_canais.getSelectedIndex(); // obter o índice do item
            DefaultListModel listach = (DefaultListModel) jList_canais.getModel(); // obter modelo de lista

            if (itemIndex > 1) {
//            listach.remove(itemIndex); // remove o item selecionado da lista
//            listach.add(itemIndex - 1, selectedItem); // adiciona o item a uma nova posição na lista
                jList_canais.setSelectedIndex(itemIndex - 1); // define a seleção para o novo item
            }

//            ControleRemotoObj.botaoacima();
//            lbl_result.setText(ControleRemotoObj.getResult());
        }
    }//GEN-LAST:event_btn_setaacimActionPerformed

    private void btn_setabaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setabaixoActionPerformed
        // TODO add your handling code here:

        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else if (jList_canais.getSelectedValue() == null) {
            ControleRemotoObj.botaobaixo();
            lbl_result.setText(ControleRemotoObj.getResult());
            lbl_result.setVisible(true);
        } else {
//            lbl_result.setVisible(false);
            // botão para mover o item jlist selecionado para baixo
            String selectedItem = jList_canais.getSelectedValue();
            int itemIndex = jList_canais.getSelectedIndex();
            DefaultListModel listach = (DefaultListModel) jList_canais.getModel();

            if (itemIndex < listach.getSize() - 1) {
//            model.remove(itemIndex);
                //           model.add(itemIndex + 1, selectedItem);
                jList_canais.setSelectedIndex(itemIndex + 1);
            }
        }

    }//GEN-LAST:event_btn_setabaixoActionPerformed

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
        // TODO add your handling code here:

        if ((ControleRemotoObj == null) || (ControleRemotoObj.getLigatv() == false)) {
//            lbl_result.setText(ControleRemotoObj.getStatusliga());
        } else if (jList_canais.getSelectedValue() == null) {
            ControleRemotoObj.botaoenter();
            lbl_result.setText(ControleRemotoObj.getResult());
            lbl_result.setVisible(true);
        } else {

            ControleRemotoObj.setNumcanal(Integer.parseInt(jList_canais.getSelectedValue()));
            lbl_canal.setText("Canal " + jList_canais.getSelectedValue());
            lbl_canal.setVisible(true);
            lbl_result.setVisible(false);
            jScrollPane1.setVisible(false);
        }
    }//GEN-LAST:event_btn_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_3d;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_a;
    private javax.swing.JButton btn_aumcan;
    private javax.swing.JButton btn_aumvol;
    private javax.swing.JButton btn_avanc;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_canlista;
    private javax.swing.JButton btn_d;
    private javax.swing.JButton btn_enter;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_futeb;
    private javax.swing.JButton btn_guia;
    private javax.swing.JButton btn_info;
    private javax.swing.JButton btn_liga;
    private javax.swing.JButton btn_lstservdds;
    private javax.swing.JButton btn_luz;
    private javax.swing.JButton btn_manual;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_more;
    private javax.swing.JButton btn_mudo;
    private javax.swing.JButton btn_parar;
    private javax.swing.JButton btn_pausa;
    private javax.swing.JButton btn_pip;
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_precan;
    private javax.swing.JButton btn_redcan;
    private javax.swing.JButton btn_redvol;
    private javax.swing.JButton btn_retroc;
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_setaacim;
    private javax.swing.JButton btn_setabaixo;
    private javax.swing.JButton btn_setadir;
    private javax.swing.JButton btn_setaesq;
    private javax.swing.JButton btn_smarthub;
    private javax.swing.JButton btn_source;
    private javax.swing.JButton btn_status;
    private javax.swing.JButton btn_tools;
    private javax.swing.JButton btn_zero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList_canais;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_canal;
    private javax.swing.JLabel lbl_ligado;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JLabel lbl_source;
    private javax.swing.JLabel lbl_volume;
    // End of variables declaration//GEN-END:variables

    Timer timer;

    private void carregacanal(String valor) {

        if (canal != "") {
            ControleRemotoObj.setPrecan((ControleRemotoObj.getNumcanal()));
        }

        if (canal.length() < 3) {
            canal = canal + valor.toString();

            if (timer != null) {
                timer.stop();

            }

            timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent arg0) {
                    ControleRemotoObj.setNumcanal(Integer.parseInt(canal));
                    lbl_canal.setText("Canal " + canal);
                    lbl_canal.setVisible(true);
                    //    lbl_canal.setText(canal);
                    canal = "";

                }

            });

            timer.setRepeats(false);
            timer.start();

        }
    }
}
